import { Sidebar } from "@/components/template/sideNav";
import { Navigation } from "@/components/template/navbar";


export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="flex flex-row min-h-screen">
          <section className="hidden md:block md:w-1/6 bg-gray-400 p-10 text-center">
            <Sidebar />
          </section>
          <section className="w-full md:w-5/6  min-h-screen py-10 px-10">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
